// Server Messages
const SUCCESS_MESSAGE = 'SUCCESS>';
const ERROR_MESSAGE = 'ERROR>';
const DATA_MESSAGE = 'DATA>';
// Client Messages
const LOGIN_MESSAGE = 'LOGIN>';
const CONNECTED_STATUS_MESSAGE = 'CONNECTED';
const CREATE_USER_MESSAGE = 'CREATE>';
const ALTER_USER_MESSAGE = 'ALTER>';
const ADD_CONTACT_MESSAGE = 'ADDCONTACT>';
const REMOVE_CONTACT_MESSAGE = 'REMOVECONTACT>';
const GET_CONTACT_LIST_MESSAGE = 'GETCONTACT';

export {
    LOGIN_MESSAGE, CONNECTED_STATUS_MESSAGE, CREATE_USER_MESSAGE, ALTER_USER_MESSAGE,
    SUCCESS_MESSAGE, ERROR_MESSAGE, ADD_CONTACT_MESSAGE, REMOVE_CONTACT_MESSAGE,
    GET_CONTACT_LIST_MESSAGE, DATA_MESSAGE
};